force-app/main/default/objects/Answer_2__c/Answer_2__c.object-meta.xml
<CustomObject>
    <label>Answer 2</label>
    <nameField>
        <label>Answer 2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer_2__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Answer 2</relationshipLabel>
    <relationshipName>Answer_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer_2__c/fields/Question_2__c.field-meta.xml
<CustomField>
    <fullName>Question_2__c</fullName>
    <label>Question 2</label>
    <referenceTo>Question_2__c</referenceTo>
    <relationshipLabel>Answer 2</relationshipLabel>
    <relationshipName>Answer_2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Answer_3__c/Answer_3__c.object-meta.xml
<CustomObject>
    <label>Answer 3</label>
    <nameField>
        <label>Answer 3 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer 3</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer_3__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Answer 3</relationshipLabel>
    <relationshipName>Answer_3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer_3__c/fields/Question_3__c.field-meta.xml
<CustomField>
    <fullName>Question_3__c</fullName>
    <label>Question 3</label>
    <referenceTo>Question_3__c</referenceTo>
    <relationshipLabel>Answer 3</relationshipLabel>
    <relationshipName>Answer_3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer 1</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Yes__c.field-meta.xml
<CustomField>
    <fullName>Yes__c</fullName>
    <label>Select</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_2__c/Question_2__c.object-meta.xml
<CustomObject>
    <label>Question 2</label>
    <nameField>
        <label>Question 2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_2__c/fields/Answer_1__c.field-meta.xml
<CustomField>
    <fullName>Answer_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer 1</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Question 2</relationshipLabel>
    <relationshipName>Question_2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_3__c/Question_3__c.object-meta.xml
<CustomObject>
    <label>Question 3</label>
    <nameField>
        <label>Question 3 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question 3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_3__c/fields/Answer_2__c.field-meta.xml
<CustomField>
    <fullName>Answer_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer 2</label>
    <referenceTo>Answer_2__c</referenceTo>
    <relationshipLabel>Question 3</relationshipLabel>
    <relationshipName>Question_3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_3__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Question 3</relationshipLabel>
    <relationshipName>Question_3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_3__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_3__c/fields/Required_Products__c.field-meta.xml
<CustomField>
    <fullName>Required_Products__c</fullName>
    <label>Required Products</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_3__c/fields/Yes__c.field-meta.xml
<CustomField>
    <fullName>Yes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Yes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question 1</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Process_Type__c</fullName>
    <label>Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GDS</fullName>
            </value>
            <value>
                <fullName>TITAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuestionsAndAnswers.cls
public class QuestionsAndAnswers {
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getQuestionsAndAnswers(){
        Map<String, Object> questionsAndAnswers = new Map<String, Object>();
        
        try{
            List<Object> processTypes = new List<Object>();
            Schema.DescribeFieldResult fieldResult = Question__c.Process_Type__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();            
            for( Schema.PicklistEntry f : ple){
                Map<String, String> processType = new Map<String, String>();
                processType.put('label', f.getLabel());
                processType.put('value', f.getValue());
                processTypes.add(processType);
            }
            questionsAndAnswers.put('processTypes', processTypes);
            
            Map<String, Question__c> question1Map = new Map<String, Question__c>([Select Id, Name, Process_Type__c, (Select Id, Name, Product_Code__c, Question__c, Question__r.Name From Answers__r Order By Sort_Order__c) From Question__c]);
            questionsAndAnswers.put('question1', question1Map);
            Map<String, Question_2__c> question2Map = new Map<String, Question_2__c>([Select Id, Name, Answer_1__c, (Select Id, Name, Product__c, Product__r.Name, Products__c, Question_2__c, Question_2__r.Name From Answer_2__r Order By Sort_Order__c) From Question_2__c]);
            questionsAndAnswers.put('question2', question2Map);
            Map<String, Question_3__c> question3Map = new Map<String, Question_3__c>([Select Id, Name, Answer_2__c, Product__c, Products__c, Required_Products__c, (Select Id, Name, Yes__c, Product__c, Product__r.Name, Products__c, Required_Products__c, Question_3__r.Name From Answer_3__r Order By Order__c) From Question_3__c Order By Order__c]);
            questionsAndAnswers.put('question3', question3Map);
            Map<String, Answer__c> answer1Map = new Map<String, Answer__c>([Select Id, Name, Product_Code__c, Question__c, (Select Id, Name, Answer_1__c From Question_2__r) From Answer__c Order By Sort_Order__c]);
            questionsAndAnswers.put('answer1', answer1Map);
            Map<String, Answer_2__c> answer2Map = new Map<String, Answer_2__c>([Select Id, Name, Product__c, Products__c, Question_2__c, (Select Id, Name, Answer_2__c, Product__c, Products__c, Required_Products__c From Question_3__r Order By Order__c) From Answer_2__c Order By Sort_Order__c]);
            questionsAndAnswers.put('answer2', answer2Map);
            Map<String, Answer_3__c> answer3Map = new Map<String, Answer_3__c>([Select Id, Name, Product__c, Products__c, Question_3__c, Required_Products__c From Answer_3__c]);
            questionsAndAnswers.put('answer3', answer3Map);
            
            questionsAndAnswers.put('isSuccess', true);
            questionsAndAnswers.put('message', '');
        } catch(Exception ex){
            questionsAndAnswers.put('isSuccess', false);
            questionsAndAnswers.put('message', ex.getMessage());
        }
        
        return questionsAndAnswers;
    }
    
    @AuraEnabled
    public static Map<String, Object> saveProductsToQuote(String quoteId, List<String> products){
        System.debug('Quote: ' + quoteId);
        System.debug('Products:' + products);
        Map<String, Object> response = new Map<String, Object>();
        List<String> productModels = new List<String>();
        
        try{
            if(String.isBlank(quoteid)){
                response.put('isSuccess', false);
                response.put('message', 'The Quote Id must be populated.');
                return response;
            }
            
            if(products.isEmpty()){
                response.put('isSuccess', false);
                response.put('message', 'The Product List must include at least one product.');
                return response;
            }
            
            SBQQ__Quote__c quote = [Select Id, SBQQ__PriceBook__c, CurrencyIsoCode From SBQQ__Quote__c Where Id = :quoteId];
            System.debug(quote);
            //the Id of the pricebook for the quote and product being added
            String pricebookId = quote.SBQQ__PriceBook__c;
            
            if(products[0].contains('-')){
                List<String> productNames = new List<String>();
                for(String product : products){
                    productNames.addAll(product.split(','));
                }
                products.clear();
                Map<String, String> productMap = new Map<String, String>();
                for(Product2 product : [Select Id, Name, ProductCode From Product2 Where ProductCode IN :productNames]){
                    productMap.put(product.ProductCode, product.Id);
                }
                for(String product : productNames){
                    products.add(productMap.get(product));
                }
            }
            
            //the currency code
            String currencyCode = quote.CurrencyIsoCode;
            
            //the JSON formatted String representing the quote model to add a product to
            String quoteModel = SBQQ.ServiceRouter.read('SBQQ.QuoteAPI.QuoteReader', quoteId);
            
            for(String s : products){
                System.debug(s);
                System.debug(pricebookId);
                System.debug(currencyCode);
                //the JSON formatted String representing the product to be added to the quote
                String productModel = SBQQ.ServiceRouter.load('SBQQ.ProductAPI.ProductLoader', s, '{"pricebookId" : "' + pricebookId + '", "currencyCode" : "' + currencyCode + '"}');
            	productModels.add(productModel);
            }
            //the JSON formatted String representing the quote with the product added to it
            String updatedQuoteModel = SBQQ.ServiceRouter.load('SBQQ.QuoteAPI.QuoteProductAdder', null, '{"quote" : ' + quoteModel + ', "products" : [' + String.join(productModels, ',') + '], "ignoreCalculate" : true}');
            
            //the JSON formatted String represeting the saved quote
            String savedQuoteModel = SBQQ.ServiceRouter.save('SBQQ.QuoteAPI.QuoteSaver', updatedQuoteModel);
            
            response.put('isSuccess', true);
            response.put('message', '');
        } catch(Exception ex){
            response.put('isSuccess', false);
            response.put('message', ex.getMessage() + '\n' + ex.getStackTraceString() + '\n' + ex.getLineNumber());
        }
        
        return response;
    }
    
}